name: basic_foss
description: "An unofficial FOSS, privacy-preserving client for Basic-Fit."

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  crypto: ^3.0.7
  app_links: ^6.4.1
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  qr: ^3.0.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "Basic-FOSS.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg